#!/usr/bin/env php
<?php
$config = (include __DIR__.'/Config.php');

if($config['psyshRootLocation'] && file_exists($config['psyshRootLocation'])){
	require_once $config['psyshRootLocation'];
}
else{
	echo 'There was a problem loading the PsySH library, check path or config';
	exit;
}

if($config['bootstrapFile']){
	require __DIR__.'/Bootstraps/'.$config['bootstrapFile'];
}

$config = new \Psy\Configuration();
$config->loadConfigFile(__DIR__.'/Config.php');

$shell = new \Psy\Shell($config);
$shell->run();
