#!/usr/bin/env php
<?php
//psysh loader
$psyLoader = require __DIR__ . '/vendor/autoload.php';

//config setup
$bootConfig = (include __DIR__.'/Config.php');

//required framework
$defaultIncludes = [
    __DIR__.'/core/tools/adapter/Adapters.php',
    __DIR__.'/core/bootstraps/'.$bootConfig['bootstrapFile']
];

//preset tools
// foreach (glob("tools/*.php") as $filename){
//     $defaultIncludes[] = $filename;
// }

$defaultIncludes[] = __DIR__."/Whiteboard.php";

$config = new \Psy\Configuration();
$config->setDefaultIncludes($defaultIncludes);
$shell = new \Psy\Shell($config);
$shell->run();