#!/usr/bin/env php
<?php
$config = (include __DIR__.'/Config.php');

if($config['psyshRootLocation'] && file_exists($config['psyshRootLocation'])){
	require_once $config['psyshRootLocation'];
}
else{
	echo 'There was a problem loading the PsySH library, check path or config';
	exit;
}

require __DIR__.'/Start.php';